mappy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('must.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

must/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'must'

urlpatterns = [
    # path('', views.IndexView.as_view()),
    # path('<int:item_id>/', views.DetailView.as_view()),
    # path('<int:pk>/', views.post_detail, name='post_detail'),
    # path('create', views.create_item, name='create_item'),
]

urlpatterns = [
	url(r'^$', views.item_list, name='item_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.item_list, name='item_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.item_detail, name='item_detail'),
]

must/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('must:item_list_by_category', args=[self.slug])


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True, null=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='must/items/%Y/%m/%d', blank=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('must:item_detail', args=[self.id, self.slug])

must/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = ['name','description','location','image']

must/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from .forms import ItemForm

from .models import Item, Category

# class IndexView(generic.ListView):
#     template_name = 'must/index.html'
#     context_object_name = 'latest_item_list'

#     def get_queryset(self):
#         #Return the last five published items.
#         return Item.objects.order_by('-created_at')[:50]


# class DetailView(generic.DetailView):
#     model = Item
    # template_name='must/detail.html'


# def post_new(request):
#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.published_date = timezone.now()
#             post.save()
#             return redirect('post_detail', pk=post.pk)
#     else:
#         form = PostForm()
#     return render(request, 'blog/post_edit.html', {'form': form})

def create_item(request):
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
    else:
        form = ItemForm()
    return render(request, 'must/create.html', {'form': form})

def item_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    items = Item.objects.filter()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = Item.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'items': items
    }
    return render(request, 'must/list.html', context)

def item_detail(request, id, slug):
    item = get_object_or_404(Item, id=id, slug=slug)
    context = {
        'item': item
    }

    return render(request, 'must/details.html', context)

must/templates/must/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}LOST&FOUND ITEMS{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'must/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'must/css/styles.css' %}">
</head>
<body>
{% include 'must/navbar.html' %}
 
{% block content %}
 
{% endblock %}
 
<script src="{% static 'must/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'must/js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

must/templates/must/create.html
{% extends 'must/base.html' %}
{% load static %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content  %}

	<form method="POST" action"" enctype="multipart/form-data">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
	    <button type="submit" class="btn btn-primary">
	      Submit
	    </button>
	  {% endbuttons %}
	</form>	

{% endblock %}

must/templates/must/detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<h1>{{ title }}</h1>

<!-- {% if error_message %}
<p>
    <strong>{{ error_message }}</strong>
</p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %} {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br /> {% endfor %}
    <input type="submit" value="Vote" />
</form> -->

</body>
</html>

must/templates/must/details.html
{% extends 'must/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Items {% endif %}
{% endblock %}
 
{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">
 
        <div class="col-sm-8 blog-main">
 
          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{% if item.image %} {{ item.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ item.name }}</h3>
                            <h6><a href="{{ item.category.get_absolute_url }}">{{ item.category }}</a></h6>
                            <p class="text-muted">Location:: {{ item.location }}</p>
                            <p>{{ item.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>
 
 
          </div><!-- /.blog-post -->
 
        </div><!-- /.blog-main -->
      </div><!-- /.row -->
 
    </div><!-- /.container -->
{% endblock %}

must/templates/must/index.html
{% extends 'must/base.html' %}
{% load static %}

{% block content  %}
<div class="container">
    <h1>ITEMS</h1>
    <div>
        <a class="btn btn-danger float-right" href="{{'create'}}"><i class="fa fa-plus fa-2x">New Item</i></a>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            {% for item in object_list %}
            <div class="card mb-3">
                <img class="card-img-top" src="{% if item.image %} {{ item.image.url }} {% else %} {% static 'must/items/default.png' %} {% endif %}" style="height: 130px; width: auto">
                <div class="card-body">
                    <h5 class="card-title">{{ item.name }}</h5>
                    <p class="card-text">{{ item.description }}</p>
                </div>
                <div class="card-footer">
                    <p class="card-text">LOCATION: {{ item.location }}</p>
                </div>
            </div>
                {% empty %}
                <div class="alert alert-warning">No Items Yet.</div>
            {% endfor %}
        </div>
        <div class="col-md-4">
            <h2>Categories</h2>
        </div>
    </div>   
</div>
{% endblock  %}

must/templates/must/list.html
{% extends 'must/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Items {% endif %}
{% endblock %}
 
{% block content %}
   <div class="container-fluid">
      <div class="row" style="margin-top: 6%">
 
        <div class="col-sm-8 blog-main">
 
          <div class="blog-post">
              <div class="row">
                  {% for item in items %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ item.get_absolute_url }}">
                                <img src="{% if item.image %} {{ item.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ item.get_absolute_url }}">{{ item.name }}</a>
                                </h3>
                                <p class="text-center">Location:: {{ item.location }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>
 
 
          </div><!-- /.blog-post -->
 
        </div><!-- /.blog-main -->
 
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'must:item_list' %}">All</a></li>
            {% for c in categories %}
 
              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->
 
      </div><!-- /.row -->
 
    </div><!-- /.container -->
{% endblock %}

must/templates/must/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <a class="navbar-brand" href="{% url 'must:item_list' %}">LOST&FOUND ITEMS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        {% if request.user.is_authenticated %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Logout</a>
          {% else %}
          <a class="dropdown-item" href="#">Sign In</a>
          <a class="dropdown-item" href="#">Sign Out</a>
        </div>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>